# Placeholders

本节介绍 tf 中 placeholders 的使用

首先引入必要的库并重置图会话

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

启动图会话

In [2]:
sess = tf.Session()

## 声明 placeholder

使用 tf.placeholder() 声明，这个函数需要一个 data-type 的参数（如：(tf.float32)）和一个 shape 参数（如：(4, 4)），shape 可以是一个 tuple 或一个 list, [4, 4]。

In [3]:
x = tf.placeholder(tf.float32, shape=(4, 4))

为解释如何使用 placeholder，我们将创建输入数据并在 tensorboard 上进行可视化操作。

feed_dict 被灌进下面代码中的 x 做为计算图的输入

In [5]:
# 灌数据到 placeholder， ‘rand_array’ 和 'x' 有相同的 shape
rand_array = np.random.rand(4, 4)

# 创建一个 tensor 用于执行操作（y 和 x 相同，是一个 4x4 矩阵）
y = tf.identity(x)

# 打印输出，用 x 的值灌进计算图
print(sess.run(y, feed_dict={x: rand_array}))

[[ 0.8980962   0.38655609  0.45680138  0.89613879]
 [ 0.73327023  0.98645008  0.97123688  0.27100194]
 [ 0.09518064  0.73233223  0.19613877  0.35742587]
 [ 0.69028497  0.67017615  0.27320266  0.17602079]]


要在 Tensorboard 可视化，我们合并概要并写进 log 文件

In [6]:
merged = tf.summary.merge_all()
writer = tf.summary.FileWriter('./variable_logs', sess.graph)

在终端中执行如下命令：

```
$ tensorboard --logdir=./
```

然后在浏览器中打开：

http://0.0.0.0:6006/

![png](./03.png)