# 矩阵及矩阵操作

本节介绍多种创建和使用矩阵的方法

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

启动图会话

In [3]:
sess = tf.Session()

## 声明矩阵

身份矩阵

In [4]:
identity_matrix = tf.diag([1.0, 1.0, 1.0])
print(sess.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


2x3 随机 normal 矩阵

In [5]:
A = tf.truncated_normal([2, 3])
print(sess.run(A))

[[ 0.85526985 -0.48161626  1.7669543 ]
 [ 0.33361295 -0.25098357  0.1590274 ]]


2x3 常数矩阵

In [6]:
B = tf.fill([2, 3], 5.0)
print(sess.run(B))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


3x2 随机 uniform 矩阵

In [7]:
C = tf.random_uniform([3, 2])
print(sess.run(C))

[[ 0.61764002  0.88779557]
 [ 0.87712514  0.8487035 ]
 [ 0.79066372  0.99283636]]


从 np array 创建矩阵

In [8]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., 7., -1.], [0., 5., -2.]]))
print(sess.run(D))

[[ 1.  2.  3.]
 [-3.  7. -1.]
 [ 0.  5. -2.]]


# 矩阵操作

矩阵加减

In [9]:
print(sess.run(A+B))
print(sess.run(A-B))

[[ 4.90232897  6.42348957  3.81232166]
 [ 5.58548546  4.67567444  3.77024722]]
[[-3.23632216 -5.93312073 -5.38330078]
 [-4.46603489 -3.14362669 -4.66481447]]


矩阵乘法

In [10]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


矩阵转置

In [11]:
print(sess.run(tf.transpose(C)))

[[ 0.37819815  0.70697725  0.99460852]
 [ 0.16747189  0.23921847  0.72366095]]


矩阵行列式

In [12]:
print(sess.run(tf.matrix_determinant(D)))

-66.0


逆矩阵

In [13]:
print(sess.run(tf.matrix_inverse(D)))

[[ 0.13636364 -0.28787879  0.34848485]
 [ 0.09090909  0.03030303  0.12121212]
 [ 0.22727273  0.07575758 -0.1969697 ]]


乔里斯基分解(Cholesky Decomposition)

In [14]:
print(sess.run(tf.cholesky(identity_matrix)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


本征值和本征向量（Eigenvalues Eigenvectors）：可使用 tf.self_adjoint_eig() 函数获得，返回两个对象，第一个是本征值数组，第二个是本征向量矩阵

In [15]:
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)
print(eigenvectors)

[ -4.52594916   0.46099679  10.06495237]
[[ 0.23777803 -0.92627235  0.29237159]
 [ 0.4379831  -0.16642126 -0.88344483]
 [-0.86696737 -0.33811758 -0.36612031]]
